# Generated by Django 2.2 on 2018-12-07 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0002_auto_20181128_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='c_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 7, 11, 6, 22, 566680)),
        ),
    ]
