# Generated by Django 2.2 on 2018-12-07 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0005_auto_20181207_1150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
